LOCAL_PATH := $(call my-dir)

# Calculator
include $(CLEAR_VARS)
LOCAL_MODULE := N_Calculator
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := system/priv-app/N_Calculator/N_Calculator.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_OVERRIDES_PACKAGES := Calculator ExactCalculator
include $(BUILD_PREBUILT)

# Clock 
include $(CLEAR_VARS)
LOCAL_MODULE := Clock
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := system/priv-app/Clock/Clock.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_OVERRIDES_PACKAGES := DeskClock
include $(BUILD_PREBUILT)

# Dialer 
include $(CLEAR_VARS)
LOCAL_MODULE := Phone
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := system/priv-app/Phone/Phone.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_OVERRIDES_PACKAGES := Dialer dialer phone
include $(BUILD_PREBUILT)

# Messaging
include $(CLEAR_VARS)
LOCAL_MODULE := N_Messaging
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := system/priv-app/N_Messaging/N_Messaging.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_OVERRIDES_PACKAGES := Messaging messaging Messages messages Message message
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)
